# Generated by Django 4.2.10 on 2024-02-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
