# Generated by Django 4.2.10 on 2024-02-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contact_remove_gallery_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number_2',
            new_name='alt_number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number_1',
            new_name='phone_number',
        ),
    ]
