# Generated by Django 4.2.10 on 2024-02-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_phone_number_2_contact_alt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
