# Generated by Django 4.2.10 on 2024-02-24 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_event_like_count_event_share_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='like_count',
        ),
        migrations.AddField(
            model_name='gallery',
            name='users_liked',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
