# Generated by Django 4.2.10 on 2024-02-24 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0007_gallery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
