# Generated by Django 4.2.10 on 2024-02-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_gallery_users_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', editable=False, max_length=10),
        ),
    ]
