# Generated by Django 4.2.10 on 2024-02-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_student_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
    ]
