# Generated by Django 4.2.10 on 2024-02-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_student_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('level1', 'Level 1'), ('level2', 'Level 2'), ('level3', 'Level 3'), ('level4', 'Level 4'), ('level5', 'Level 5'), ('level6', 'Level 6')], default='level1', max_length=20),
        ),
    ]
